name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - huseyin
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
      - name: Build Web App
        run: npx expo export -p web
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          channelId: live
          projectId: caltrackr-b020f
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
